title: Yingjian Liang

url: https://yingjianliang567.github.io

owner:
  name: Yingjian Liang
  avatar: /images/avatar.jpg
  email: yingjianliang@hrbmu.edu.cn
  github: yingjianliang567
  linkedin: larry-deng-317b92360
  scholar: https://scholar.google.com/citations?hl=en&user=aKyLtgsAAAAJ
  researchgate: https://www.researchgate.net/profile/Siming-Deng-3


links:
  - title: About Me
    url: /
  - title: Publications
    url: /publications/


timezone: Asia/Shanghai

future: true

highlighter: rouge

permalink: /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6